# Preface {.unnumbered}

This "book" is basically a set of handouts generated for a Data Science in Education course taught at the Harvard Graduate School of Education by Luke Miratrix. They are loosely organized, but the primary purpose of this "book" is to make all the handouts easy to access and find.

The handouts were generated in response to student questions, and aim to short-circuit staring at the possibly confusing world of Stack Overflow. They are curated in the sense that these activities tend to come up over and over in the course of fundamental data science work.

I hope you find this resource useful. Please send feedback to `lmiratrix@g.harvard.edu`.

## A note on duplicated material

Some of this material is taken from a sister "textbook" for my MLM course (S043/Stat151). That textbook is [here](https://lmiratrix.github.io/MLM/). In particular, you will find entire chapters of that textbook replicated here.

## About Statistical Programming

Statistical programming entails using a computer to analyze data in a way where you design and control the analysis and sometimes aspects of data generation (simulation). This is a step (or possibly several steps) beyond simply running built-in commands and interpreting output. It includes cleaning and transforming data to suit your needs, designing visualizations and plots to illustrate points you want to make, and conducting analyses that are tailor-made to your questions of interest.

S022 will make extensive use of the statistical software package R, which runs on both PCs and Macs. The software is [free and available online](http://www.r-project.org/). R is straightforward to learn, but is sufficiently powerful and versatile to be useful for real projects that you might carry out after this course. It is used widely in many other statistics courses and also in research in such fields as education, psychology, economics, medical research, epidemiology, public health, and political science. See below for further argument as to why you should learn R.

We highly recommend using RStudio, which makes using R easier. RStudio is an Integrated Development Environment (IDE) that structures your experience, helps keep things organized, and offers multiple time-saving features to make your programming experience better. You might also consider R Markdown. R Markdown allows for generating documents with embedded R code and R output in a clean format, which can greatly help report generation.

We will teach R and the associated tools as part of this course. We assume no background knowledge with statistical programming or any other programming.

## The R Mystique

Many people seem to believe that R is particularly technically challenging and difficult to master. This probably stems from its extreme flexibility; it is a fully functional programming language as well as a statistical analysis package. R can do things that many other software packages (I’m looking at you, Stata) essentially can’t. These more involved things are frequently hard to do because they require you to think like a programmer rather than a data analyst. As a result, R is perceived as a "hard" language to use.

However, for straightforward, off-the-shelf analyses, R is arguably easier to learn and use in many ways than programs such as Stata or SAS. This is especially true when R is combined with RStudio for a better programming experience.

Don't believe me? Take S022, have us teach you some R, and find out for yourself.
